version: '3'
services:
  magic:
    image: mageai/mageai:latest
    command: mage start ${PROJECT_NAME}
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      USER_CODE_PATH: /home/mzfuadi/zoomcamp-perikanan-indonesia/02-mage/${PROJECT_NAME}
      ENV: ${ENV}
    ports:
      - 6789:6789
    volumes:
    
      - .:/home/mzfuadi/zoomcamp-perikanan-indonesia/02-mage/${PROJECT_NAME}
      - ../credentials:/home/src/credentials 
    restart: on-failure:5